In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
import glob
import pickle

from sklearn import tree
from sklearn import svm
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.preprocessing import normalize

In [2]:
from datagen import DataGen

In [3]:
folder_name='data/historical_price_data'
bar_type='time'             #type of bars possible_values: dollar,time,ticks,volume
threshold=300               #threshold for the given type of bar

#normalization
before=False                #flag that denotes normalizing before/after bars creation
normalize=False             #flag that specifies whether normalization should be done
norm_method='multiply'     #method for nomalization include 'multiply','min_max'
norm_val=100               #threshold for the above mentioned method


# Labels
volatility_threshold=20    #threshold in bars for volatility which is standard deviation of returns
sampling=False             #flag to control downsampling
v_bars_duration=20           #threshold in bars for vertical_bars which denotes a dataframe in triple-barrier method
barrier_conf=[2,4]          #stop loss and profit taking limits [0]denotes stop loss and [1]denotes profit taking
min_return=0                #minimum values for return in triple-barrier method
risk=0                      #risk for calculating sharp_ration
sign_label=True             #flag to determine labels of vertical bars t1b

# Features
sma_period = [10, 20] # [10, 15, 20]
ema_period = [10, 20] # [10, 15, 20]
BB_period  = [15]
rsi_period = [15]
williamsr_period = [15]
roc_period = [15]
adl_period = [15]
vpt_period = [0] # 0:  period is not required
emv_period = [0] # 0:  period is not required

feature_list = ['sma',      'ema',    'BB',       'rsi',     'williamsr',        'roc', 
                'adl',     'vpt',   'emv']   #feature list 
period_all =[sma_period, ema_period, BB_period, rsi_period, williamsr_period, roc_period, 
             adl_period, vpt_period, emv_period ]  # feature list period (change this if feature_list_changed)

In [4]:
test=DataGen()

In [5]:
un_raw_data,un_labels,un_labels_features=test.create_data(folder_name,feature_list,period_all,before,normalize,norm_val,norm_method,bar_type,threshold,sampling,volatility_threshold,v_bars_duration,
                            barrier_conf,min_return,risk,sign_label)

[Errno 2] No such file or directory: 'saved_runs/MAIN_df_ADABTC'
[Errno 2] No such file or directory: 'saved_runs/cstk_df_ADABTC_time_300_False_False_100_multiply'
[Errno 2] No such file or directory: 'saved_runs/Labels_ADABTC_False_False_100_multiply_20_[2, 4]_0'

2019-02-15 15:30:59.741065 100.0% triple_barrier_single done after 0.36 minutes. Remaining 0.0 minutes..

[Errno 2] No such file or directory: "saved_runs/features_ADABTC_False_False_100_multiply_['sma', 'ema', 'BB', 'rsi', 'williamsr', 'roc', 'adl', 'vpt', 'emv']_[[10, 20], [10, 20], [15], [15], [15], [15], [15], [0], [0]]"
                 Date     Close
0 2017-11-30 12:29:00  0.000089
1 2017-11-30 12:34:00  0.000011
2 2017-11-30 12:39:00  0.000012
3 2017-11-30 12:44:00  0.000012
4 2017-11-30 12:49:00  0.000012
Labels:  -1.0    29387
 1.0    15168
Name: label, dtype: int64
[Errno 2] No such file or directory: 'saved_runs/MAIN_df_BTCUSDT'
[Errno 2] No such file or directory: 'saved_runs/cstk_df_BTCUSDT_time_300_False_False_100_multiply'
[Errno 2] No such file or directory: 'saved_runs/Labels_BTCUSDT_False_False_100_multiply_20_[2, 4]_0'

2019-02-15 15:33:08.286902 100.0% triple_barrier_single done after 0.38 minutes. Remaining 0.0 minutes..

[Errno 2] No such file or directory: "saved_runs/features_BTCUSDT_False_False_100_multiply_['sma', 'ema', 'BB', 'rsi', 'williamsr', 'roc', 'adl', 'vpt', 'emv']_[[10, 20], [10, 20], [15], [15], [15], [15], [15], [0], [0]]"
                 Date    Close
0 2017-08-17 04:00:00  4261.48
1 2017-08-17 04:05:00  4261.48
2 2017-08-17 04:10:00  4261.48
3 2017-08-17 04:15:00  4261.48
4 2017-08-17 04:20:00  4266.29

/home/siba/repos/mlframework/v1/feature/featureExtraction.py:925: RuntimeWarning:

invalid value encountered in double_scalars

Labels:  -1.0    28143
 1.0    16019
Name: label, dtype: int64

In [6]:
un_raw_data.head()

,DateStop,Open,High,Low,Close,Volume,Price
0,2017-11-30 12:33:00,0.000009,0.000089,0.000009,0.000089,2375.0,0.000025
1,2017-11-30 12:38:00,0.000088,0.000088,0.000011,0.000011,404606.0,0.000034
2,2017-11-30 12:43:00,0.000011,0.000012,0.000011,0.000012,962283.0,0.000012
3,2017-11-30 12:48:00,0.000012,0.000014,0.000012,0.000012,1284517.0,0.000013
4,2017-11-30 12:53:00,0.000012,0.000013,0.000012,0.000012,1907264.0,0.000013

In [7]:
len(un_raw_data)

110424

In [8]:
un_labels.head()

,close,return,volatility,type,vbars,ret,label,sharp_ratio,profit
0,0.000012,-0.660375,0.727906,t1,2017-11-30 14:19:00,0.020647,0.0,-0.907225,1.0
1,0.000013,0.082932,0.523736,t1,2017-11-30 14:24:00,-0.041150,0.0,0.158347,1.0
2,0.000013,-0.000159,0.418622,t1,2017-11-30 14:29:00,-0.032735,0.0,-0.000380,1.0
3,0.000012,-0.011918,0.353684,t1,2017-11-30 14:34:00,-0.005146,0.0,-0.033697,1.0
4,0.000012,-0.039884,0.307959,t1,2017-11-30 14:39:00,0.009715,0.0,-0.129511,1.0

In [9]:
un_labels_features.head()

,Close,sma_10,sma_20,ema_10,ema_20,BB_15,rsi_15,williamsr_15,roc_15,adl_15,vpt_0,emv_0,label
0,0.000012,0.000012,0.000012,0.000012,0.000012,0.000012,73.888889,-33.333333,4.303797,-3.276130e+05,12075.179129,1.523409e-14,-1.0
1,0.000012,0.000012,0.000012,0.000012,0.000012,0.000012,76.904177,-17.592593,3.694374,-1.011443e+07,-620.390777,1.355359e-14,-1.0
2,0.000013,0.000012,0.000012,0.000012,0.000012,0.000012,75.132275,-24.074074,5.387205,-1.585562e+07,6533.478543,2.068163e-14,-1.0
3,0.000012,0.000012,0.000012,0.000012,0.000012,0.000013,79.262673,-26.851852,3.750000,-1.585562e+07,-2632.357827,2.135994e-14,-1.0
4,0.000012,0.000012,0.000012,0.000012,0.000012,0.000013,79.629630,-15.533981,1.886792,-1.306207e+07,-438.493976,2.247437e-14,-1.0

In [10]:
un_labels_features[un_labels_features.williamsr_15<-101]

Empty DataFrame
Columns: [Close, sma_10, sma_20, ema_10, ema_20, BB_15, rsi_15, williamsr_15, roc_15, adl_15, vpt_0, emv_0, label]
Index: []

In [11]:
un_labels_features[un_labels_features.rsi_15>100]

,Close,sma_10,sma_20,ema_10,ema_20,BB_15,rsi_15,williamsr_15,roc_15,adl_15,vpt_0,emv_0,label
805,0.000011,0.000011,0.000011,0.000011,0.000011,0.000011,100.0,-78.571429,1.684397,3.191951e+08,223.802643,8.947914e-15,1.0
806,0.000012,0.000011,0.000011,0.000011,0.000011,0.000011,100.0,-57.142857,1.590106,3.214104e+08,182.641674,1.249812e-14,1.0
807,0.000012,0.000011,0.000011,0.000011,0.000011,0.000012,100.0,-78.666667,2.824360,3.230878e+08,633.117391,1.772126e-14,1.0
808,0.000012,0.000011,0.000011,0.000011,0.000011,0.000012,100.0,-60.000000,1.588703,3.246285e+08,-2051.690987,2.529649e-14,1.0
809,0.000012,0.000011,0.000011,0.000011,0.000011,0.000012,100.0,-88.888889,2.824360,3.261396e+08,149.098175,1.667086e-14,1.0
35813,0.000037,0.000037,0.000036,0.000037,0.000037,0.000037,100.0,-97.546012,2.940361,1.926996e+10,-488.452586,3.088762e-14,1.0
35814,0.000037,0.000037,0.000036,0.000037,0.000037,0.000037,100.0,-98.159509,3.022740,1.927130e+10,1447.430881,2.978130e-14,1.0
35815,0.000037,0.000037,0.000037,0.000037,0.000037,0.000037,100.0,-72.049689,2.909393,1.927725e+10,-220.368506,2.670647e-14,1.0

In [12]:
folder_name='data/historical_price_data'
bar_type='time'             #type of bars possible_values: dollar,time,ticks,volume
threshold=300               #threshold for the given type of bar

#normalization
before=True                #flag that denotes normalizing before/after bars creation
normalize=True             #flag that specifies whether normalization should be done
norm_method='multiply'     #method for nomalization include 'multiply','min_max'
norm_val=100               #threshold for the above mentioned method


# Labels
volatility_threshold=20    #threshold in bars for volatility which is standard deviation of returns
sampling=False             #flag to control downsampling
v_bars_duration=20           #threshold in bars for vertical_bars which denotes a dataframe in triple-barrier method
barrier_conf=[2,4]          #stop loss and profit taking limits [0]denotes stop loss and [1]denotes profit taking
min_return=0                #minimum values for return in triple-barrier method
risk=0                      #risk for calculating sharp_ration
sign_label=True             #flag to determine labels of vertical bars t1b

# Features
sma_period = [10, 20] # [10, 15, 20]
ema_period = [10, 20] # [10, 15, 20]
BB_period  = [15]
rsi_period = [15]
williamsr_period = [15]
roc_period = [15]
adl_period = [15]
vpt_period = [0] # 0:  period is not required
emv_period = [0] # 0:  period is not required

feature_list = ['sma',      'ema',    'BB',       'rsi',     'williamsr',        'roc', 
                'adl',     'vpt',   'emv']   #feature list 
period_all =[sma_period, ema_period, BB_period, rsi_period, williamsr_period, roc_period, 
             adl_period, vpt_period, emv_period ]  # feature list period (change this if feature_list_changed)

In [13]:
raw_data,labels,labels_features=test.create_data(folder_name,feature_list,period_all,before,normalize,norm_val,norm_method,bar_type,threshold,sampling,volatility_threshold,v_bars_duration,
                            barrier_conf,min_return,risk,sign_label)

[Errno 2] No such file or directory: 'saved_runs/MAIN_df_ADABTC_normalized_main_df_True_True_100_multiply'
[Errno 2] No such file or directory: 'saved_runs/cstk_df_ADABTC_time_300_True_True_100_multiply'
[Errno 2] No such file or directory: 'saved_runs/Labels_ADABTC_True_True_100_multiply_20_[2, 4]_0'

2019-02-15 15:35:10.439235 100.0% triple_barrier_single done after 0.46 minutes. Remaining 0.0 minutes..

[Errno 2] No such file or directory: "saved_runs/features_ADABTC_True_True_100_multiply_['sma', 'ema', 'BB', 'rsi', 'williamsr', 'roc', 'adl', 'vpt', 'emv']_[[10, 20], [10, 20], [15], [15], [15], [15], [15], [0], [0]]"
                 Date       Close
0 2017-11-30 12:29:00  273.326819
1 2017-11-30 12:34:00   35.010402
2 2017-11-30 12:39:00   36.238837
3 2017-11-30 12:44:00   37.221585
4 2017-11-30 12:49:00   37.743670
Labels:  -1.0    29387
 1.0    15168
Name: label, dtype: int64
[Errno 2] No such file or directory: 'saved_runs/MAIN_df_BTCUSDT_normalized_main_df_True_True_100_multiply'
[Errno 2] No such file or directory: 'saved_runs/cstk_df_BTCUSDT_time_300_True_True_100_multiply'
[Errno 2] No such file or directory: 'saved_runs/Labels_BTCUSDT_True_True_100_multiply_20_[2, 4]_0'

2019-02-15 15:37:19.709690 100.0% triple_barrier_single done after 0.41 minutes. Remaining 0.0 minutes..

[Errno 2] No such file or directory: "saved_runs/features_BTCUSDT_True_True_100_multiply_['sma', 'ema', 'BB', 'rsi', 'williamsr', 'roc', 'adl', 'vpt', 'emv']_[[10, 20], [10, 20], [15], [15], [15], [15], [15], [0], [0]]"
                 Date      Close
0 2017-08-17 04:00:00  49.635903
1 2017-08-17 04:05:00  49.635903
2 2017-08-17 04:10:00  49.635903
3 2017-08-17 04:15:00  49.635903
4 2017-08-17 04:20:00  49.691928

/home/siba/repos/mlframework/v1/feature/featureExtraction.py:925: RuntimeWarning:

invalid value encountered in double_scalars

Labels:  -1.0    28143
 1.0    16019
Name: label, dtype: int64

In [14]:
raw_data.head()

,DateStop,Open,High,Low,Close,Volume,Price
0,2017-11-30 12:33:00,27.639791,273.326819,27.639791,273.326819,2.728835,76.777196
1,2017-11-30 12:38:00,270.255731,270.255731,35.010402,35.010402,464.885415,105.111053
2,2017-11-30 12:43:00,33.874099,36.668789,33.781966,36.238837,1105.646806,35.698325
3,2017-11-30 12:48:00,36.515235,42.995230,35.931728,37.221585,1475.888193,38.658854
4,2017-11-30 12:53:00,37.221585,40.384805,36.791632,37.743670,2191.413908,38.652712

In [15]:
len(raw_data)

110424

In [16]:
labels.head(100)

,close,return,volatility,type,vbars,ret,label,sharp_ratio,profit
0,35.698325,-6.603752e-01,0.727906,t1,2017-11-30 14:19:00,0.020647,0.0,-9.072253e-01,1.0
1,38.658854,8.293187e-02,0.523736,t1,2017-11-30 14:24:00,-0.041150,0.0,1.583468e-01,1.0
2,38.652712,-1.588815e-04,0.418622,t1,2017-11-30 14:29:00,-0.032735,0.0,-3.795343e-04,1.0
3,38.192049,-1.191800e-02,0.353684,t1,2017-11-30 14:34:00,-0.005146,0.0,-3.369675e-02,1.0
4,36.668789,-3.988421e-02,0.307959,t1,2017-11-30 14:39:00,0.009715,0.0,-1.295113e-01,1.0
5,34.985833,-4.589615e-02,0.273556,t1,2017-11-30 14:44:00,0.060393,0.0,-1.677760e-01,1.0
6,35.698325,2.036517e-02,0.247734,t1,2017-11-30 14:49:00,0.059532,0.0,8.220591e-02,1.0
7,35.569340,-3.613214e-03,0.225602,t1,2017-11-30 14:54:00,0.042134,0.0,-1.601585e-02,1.0
8,35.716752,4.144362e-03,0.207085,t1,2017-11-30 14:59:00,0.035942,0.0,2.001288e-02,1.0
9,35.274515,-1.238177e-02,0.190900,t1,2017-11-30 15:04:00,0.035173,0.0,-6.485994e-02,1.0
10,35.802742,1.497475e-02,0.177254,t1,2017-11-30 15:09:00,0.013210,0.0,8.448170e-02,1.0
11,35.335937,-1.303826e-02,0.164745,t1,2017-11-30 15:14:00,0.027985,0.0,-7.914225e-02,1.0
12,34.826136,-1.442726e-02,0.153589,t1,2017-11-30 15:19:00,0.032804,0.0,-9.393436e-02,1.0
13,35.237662,1.181658e-02,0.143874,t1,2017-11-30 15:24:00,0.022660,0.0,8.213131e-02,1.0
14,34.936695,-8.541049e-03,0.134778,t1,2017-11-30 15:29:00,0.046941,0.0,-6.337136e-02,1.0
15,34.629587,-8.790436e-03,0.126489,t1,2017-11-30 15:34:00,0.058531,0.0,-6.949575e-02,1.0
16,34.875274,7.094714e-03,0.119057,t1,2017-11-30 15:39:00,0.048080,0.0,5.959107e-02,1.0
17,35.010402,3.874604e-03,0.112148,t1,2017-11-30 15:44:00,0.048421,0.0,3.454899e-02,1.0
18,35.274515,7.543860e-03,0.105806,t1,2017-11-30 15:49:00,0.041616,0.0,7.129907e-02,1.0
19,35.557055,8.009751e-03,0.099918,t1,2017-11-30 15:54:00,0.024875,0.0,8.016313e-02,1.0
20,36.435386,2.470202e-02,0.094813,t1,2017-11-30 15:59:00,0.001517,0.0,2.605351e-01,1.0
21,37.068030,1.736345e-02,0.089796,t1,2017-11-30 16:04:00,-0.020050,0.0,1.933647e-01,1.0
22,37.387424,8.616404e-03,0.084952,t1,2017-11-30 16:09:00,-0.030557,0.0,1.014263e-01,1.0
23,37.995499,1.626417e-02,0.080521,t1,2017-11-30 16:14:00,-0.042354,0.0,2.019876e-01,1.0
24,37.025035,-2.554155e-02,0.076743,t1,2017-11-30 16:19:00,-0.008792,0.0,-3.328194e-01,1.0
25,37.098741,1.990710e-03,0.072692,t1,2017-11-30 16:24:00,-0.011424,0.0,2.738554e-02,1.0
26,37.823518,1.953642e-02,0.069147,t1,2017-11-30 16:29:00,-0.032640,0.0,2.825350e-01,1.0
27,37.068030,-1.997402e-02,0.065902,t1,2017-11-30 16:34:00,0.000994,0.0,-3.030875e-01,1.0
28,37.000466,-1.822701e-03,0.062495,t1,2017-11-30 16:39:00,0.013612,0.0,-2.916541e-02,1.0
29,36.515235,-1.311421e-02,0.059412,t1,2017-11-30 16:44:00,0.022540,0.0,-2.207343e-01,1.0
...,...,...,...,...,...,...,...,...,...
70,36.128278,-2.543666e-03,0.013207,t1,2017-11-30 20:09:00,-0.025162,0.0,-1.925961e-01,1.0
71,36.619652,1.360082e-02,0.013597,sl,2017-11-30 20:04:00,-0.031533,-1.0,1.000312e+00,1.0
72,36.779348,4.360953e-03,0.013075,sl,2017-11-30 20:04:00,-0.035738,-1.0,3.335448e-01,1.0
73,36.779348,2.220446e-16,0.012443,sl,2017-11-30 20:04:00,-0.035738,-1.0,1.784456e-14,1.0
74,36.920618,3.841015e-03,0.011936,sl,2017-11-30 19:54:00,-0.024954,-1.0,3.218120e-01,1.0
75,36.607367,-8.484445e-03,0.011587,sl,2017-11-30 20:04:00,-0.031208,-1.0,-7.322435e-01,1.0
76,36.631936,6.711409e-04,0.011041,sl,2017-11-30 20:04:00,-0.031858,-1.0,6.078681e-02,1.0
77,36.625794,-1.676727e-04,0.010507,sl,2017-11-30 20:04:00,-0.031695,-1.0,-1.595753e-02,1.0
78,36.644220,5.031025e-04,0.010008,sl,2017-11-30 20:04:00,-0.032182,-1.0,5.027202e-02,1.0
79,36.539803,-2.849480e-03,0.009535,sl,2017-11-30 20:04:00,-0.029417,-1.0,-2.988594e-01,1.0
80,36.177415,-9.917633e-03,0.009440,sl,2017-11-30 20:04:00,-0.019694,-1.0,-1.050564e+00,1.0
81,36.613509,1.205433e-02,0.009933,sl,2017-11-30 20:04:00,-0.031371,-1.0,1.213588e+00,1.0
82,36.662647,1.342057e-03,0.009468,sl,2017-11-30 20:04:00,-0.032669,-1.0,1.417487e-01,1.0
83,36.244979,-1.139219e-02,0.009584,sl,2017-11-30 20:04:00,-0.021522,-1.0,-1.188668e+00,1.0
84,36.195841,-1.355702e-03,0.009116,sl,2017-11-30 20:04:00,-0.020193,-1.0,-1.487123e-01,1.0
85,36.171273,-6.787714e-04,0.008675,sl,2017-11-30 20:04:00,-0.019528,-1.0,-7.824482e-02,1.0
86,36.122135,-1.358465e-03,0.008252,sl,2017-11-30 20:04:00,-0.018194,-1.0,-1.646323e-01,1.0
87,35.999292,-3.400782e-03,0.007871,sl,2017-11-30 20:09:00,-0.021669,-1.0,-4.320669e-01,1.0
88,36.005434,1.706193e-04,0.007506,sl,2017-11-30 20:09:00,-0.021836,-1.0,2.273046e-02,1.0
89,35.464923,-1.501194e-02,0.008225,tp,2017-11-30 20:59:00,0.037063,1.0,-1.825104e+00,0.0
90,35.219236,-6.927607e-03,0.007925,tp,2017-11-30 20:29:00,0.031740,1.0,-8.741958e-01,0.0
91,35.219236,2.220446e-16,0.007597,tp,2017-11-30 20:29:00,0.031740,1.0,2.922833e-14,0.0
92,35.366648,4.185560e-03,0.007530,tp,2017-11-30 20:49:00,0.031435,1.0,5.558692e-01,0.0
93,35.944012,1.632511e-02,0.009074,tp,2017-11-30 21:44:00,0.048189,1.0,1.799098e+00,0.0
94,36.337111,1.093643e-02,0.009283,t1,2017-11-30 22:09:00,0.006254,0.0,1.178089e+00,0.0
95,36.380107,1.183232e-03,0.008831,tp,2017-11-30 21:44:00,0.035624,1.0,1.339799e-01,0.0
96,36.281832,-2.701334e-03,0.008463,tp,2017-11-30 21:44:00,0.038429,1.0,-3.191854e-01,0.0
97,36.158988,-3.385813e-03,0.008130,tp,2017-11-30 21:44:00,0.041957,1.0,-4.164530e-01,0.0
98,36.478382,8.833022e-03,0.008175,tp,2017-11-30 21:44:00,0.032834,1.0,1.080509e+00,0.0
99,36.509092,8.418926e-04,0.007776,tp,2017-11-30 21:44:00,0.031965,1.0,1.082703e-01,0.0

In [17]:
labels_features.head(100)

,Close,sma_10,sma_20,ema_10,ema_20,BB_15,rsi_15,williamsr_15,roc_15,adl_15,vpt_0,emv_0,label
0,37.958646,37.347499,36.946722,37.327542,37.731653,38.053809,73.888889,-33.333333,4.303797,-376.421737,13.874176,125.051084,-1.0
1,37.927935,37.458059,37.003538,37.436704,37.750346,38.137139,76.904177,-17.592593,3.694374,-11621.311515,-0.712818,111.256459,-1.0
2,38.450020,37.587044,37.107955,37.620944,37.816982,38.375821,75.132275,-24.074074,5.387205,-18217.841270,7.506856,169.767939,-1.0
3,38.235044,37.657679,37.197016,37.732598,37.856797,38.454979,79.262673,-26.851852,3.750000,-18217.841270,-3.024534,175.335941,-1.0
4,38.142911,37.716030,37.302969,37.807201,37.884046,38.526764,79.629630,-15.533981,1.886792,-15008.095255,-0.503822,184.483906,-1.0
5,38.388598,37.795878,37.418134,37.912909,37.932099,38.673443,75.690608,-12.000000,4.253545,-11733.909463,3.357036,87.137509,-1.0
6,38.419309,37.906437,37.519480,38.004982,37.978500,38.746793,75.070822,-10.000000,3.388430,-7002.705764,0.265891,124.774686,-1.0
7,38.480731,38.050779,37.614684,38.091482,38.026331,38.845599,69.736842,-27.000000,2.536825,-5459.473811,1.497346,137.912817,-1.0
8,37.958646,38.133698,37.688390,38.067330,38.019885,38.861226,72.941176,-37.113402,1.062960,-13707.208458,-6.096996,143.288443,-1.0
9,37.590115,38.155195,37.725243,37.980563,37.978955,38.860711,68.131868,-15.873016,0.000000,-16332.862194,-4.898750,56.452994,-1.0
10,37.344428,38.093774,37.720637,37.864903,37.918524,38.871570,59.961315,-10.909091,0.082305,-9766.007283,-1.790671,6.783356,-1.0
11,37.221585,38.023139,37.740599,37.747936,37.852148,38.880252,50.903120,-100.000000,0.497512,-9766.007283,-1.601078,-36.495750,-1.0
12,37.098741,37.415063,37.565547,37.112499,37.448439,39.397460,37.450723,-43.396226,-2.265372,-27975.596757,16.029389,-124.294933,-1.0
13,36.607367,37.236940,37.516409,37.020657,37.368337,39.379047,38.261997,-28.846154,-3.481781,-23448.490126,-6.321065,-105.308283,-1.0
14,36.822343,37.077244,37.491841,36.984600,37.316337,39.332275,38.580645,-22.448980,-4.233227,-31941.998792,5.795098,-166.953137,-1.0
15,36.791632,36.908334,37.479556,36.949515,37.266365,39.174136,33.426573,-56.521739,-3.775100,-38267.415608,-0.277988,-171.077515,-1.0
16,36.208126,36.733282,37.433490,36.814717,37.165581,39.069209,36.088154,-4.411765,-5.072464,-31047.208750,-10.361572,-286.041475,-1.0
17,36.914476,36.665718,37.410457,36.832855,37.141666,38.924268,32.503277,-9.375000,-3.840000,-37874.922694,6.477209,-265.545464,-1.0
18,36.668789,36.598154,37.345964,36.803025,37.096630,38.688098,27.566807,-7.812500,-4.556355,-40284.197066,-0.883444,-249.005092,-1.0
19,36.699500,36.545945,37.284542,36.784202,37.058808,38.393921,29.787234,-31.250000,-4.628891,-44030.854673,0.358832,-268.963085,-1.0
20,36.238837,36.598154,37.173983,36.685045,36.980716,38.006253,22.742475,-40.625000,-4.530744,-49853.349813,-1.679486,-271.146815,-1.0
21,36.054571,36.610438,37.064959,36.570413,36.892511,37.745888,23.407917,-4.687500,-4.084967,-43642.909198,-2.256519,-272.323300,-1.0
22,36.760922,36.576656,36.995860,36.605051,36.879979,37.564889,24.242424,-18.750000,-1.562500,-41678.126155,4.170812,-187.828618,-1.0
23,36.484524,36.564372,36.900656,36.583137,36.842317,37.416772,38.619403,-32.812500,-1.980198,-38149.955554,-3.851287,-147.073695,-1.0
24,36.208126,36.502950,36.790097,36.514953,36.781917,37.279541,40.413534,-34.375000,1.375752,-45200.694314,-7.433189,-102.546697,-1.0
25,36.177415,36.441528,36.674931,36.453583,36.724346,37.214093,50.469484,-34.375000,0.683761,-45494.566498,-0.362718,-90.460776,-1.0
26,36.177415,36.438457,36.585870,36.403370,36.672257,37.182419,51.312649,-42.105263,-2.483444,-40143.683335,0.000000,-123.477276,-1.0
27,35.901017,36.337111,36.501415,36.312033,36.598806,37.096120,39.358601,-49.275362,-1.929530,-41326.593139,-7.240647,-155.228973,-1.0
28,35.962439,36.266476,36.432315,36.248471,36.538199,37.092098,33.538462,-52.173913,-2.335279,-43160.486050,1.078686,-140.865334,-1.0
29,35.901017,36.186628,36.366287,36.185297,36.477515,37.035364,31.594203,-95.652174,-2.420701,-39024.735998,-0.793049,-154.335415,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,37.037320,38.001641,37.565547,37.728792,37.575186,39.114499,55.081001,-25.274725,-0.165563,6037.184350,-2.937861,-74.077060,-1.0
71,37.160163,37.937148,37.582438,37.625405,37.535660,39.108567,50.515464,-16.000000,0.331675,9733.954199,1.492958,-3.288075,-1.0
72,37.006609,37.826589,37.613148,37.512896,37.485274,39.112298,54.482759,-5.970149,-0.823045,11495.293743,-1.119314,-69.377169,-1.0
73,37.006609,37.719101,37.628504,37.420844,37.439687,39.138226,49.267643,-59.701493,-2.665590,7029.141994,0.000000,-116.042583,-1.0
74,35.901017,37.378210,37.597793,37.144512,37.293147,39.325221,41.449275,-12.962963,-6.104418,-31.726199,-12.336416,-206.038655,-1.0
75,36.515235,37.175518,37.565547,37.030098,37.219060,39.285672,34.139599,-16.666667,-3.411860,-6269.518721,14.186805,-229.503235,-1.0
76,36.453813,37.058817,37.533300,36.925319,37.146180,39.283374,34.887006,-24.074074,-4.351330,-10360.913318,-0.295554,-228.832828,-1.0
77,36.330969,36.871481,37.497983,36.817255,37.068541,39.221057,28.549383,-26.000000,-4.596774,-10360.913318,-0.776410,-226.073896,-1.0
78,36.208126,36.690287,37.442703,36.706504,36.986596,39.141083,29.658385,-74.137931,-7.890625,-16083.893453,-1.609998,-341.563807,-1.0
79,35.686041,36.380107,37.190874,36.346318,36.737436,38.407212,9.430894,-81.818182,-5.142857,-13252.762950,1.928703,-367.310413,1.0
80,35.747463,36.238837,37.087992,36.237435,36.643153,38.299255,10.000000,-69.444444,-6.430868,-20551.507391,0.834033,-238.707664,1.0
81,36.208126,36.085282,36.731746,36.190953,36.510159,37.383621,32.270916,-60.869565,-2.238806,-29933.495990,2.034648,-122.207833,1.0
82,35.778173,35.990079,36.430780,36.140898,36.403349,36.896823,34.382567,-78.000000,-3.319502,-27969.074275,-4.363824,-170.336263,1.0
83,36.085282,35.977794,36.334040,36.130786,36.373057,36.664238,33.569740,-94.117647,0.513259,-21620.361829,2.436702,-95.471490,1.0
84,35.839595,36.008505,36.261870,36.077842,36.322251,36.666313,38.430311,-76.470588,-1.850294,-19075.803861,-4.398029,-73.425224,1.0
85,36.115993,36.051500,36.215804,36.084779,36.302608,36.588502,38.797814,-93.617021,-0.926706,-19991.893257,3.781454,-88.543651,1.0
86,36.054571,36.082211,36.160524,36.079286,36.278985,36.513443,41.114058,-67.441860,-0.760778,-26408.600219,-1.902679,-90.677282,1.0
87,36.515235,36.125206,36.135955,36.158550,36.301485,36.566363,40.322581,-92.105263,0.848176,-21088.808022,10.324097,-34.332691,1.0
88,36.699500,36.432315,36.205055,36.524302,36.462462,37.003009,68.773234,-40.000000,1.357082,-23279.012699,-4.025810,43.518826,-1.0
89,37.098741,36.558230,36.283367,36.628745,36.523060,37.165353,74.460432,-40.000000,2.199662,-32695.738396,8.833599,36.412360,-1.0
90,37.098741,36.656505,36.354002,36.714199,36.577887,37.297716,73.507463,-31.034483,2.286198,-22286.112148,0.000000,38.426921,-1.0
91,37.129452,36.763993,36.423102,36.789700,36.630417,37.418086,72.586873,-17.241379,3.776824,-11700.528346,0.463563,73.372184,-1.0
92,37.252296,36.837699,36.481453,36.873808,36.689643,37.500236,84.615385,-10.344828,3.234043,-21150.456061,2.759749,76.829823,-1.0
93,37.313717,36.935974,36.542874,36.953792,36.749079,37.604970,92.148760,-25.714286,4.113111,-10214.572621,2.026444,76.829823,-1.0
94,37.129452,36.985111,36.588941,36.985730,36.785305,37.589880,94.650206,-22.857143,2.806122,-3594.737415,-6.337694,76.629812,-1.0
95,37.160163,37.055746,36.631936,37.017445,36.821006,37.597791,90.416667,-0.000000,3.066440,-11291.462757,0.985335,75.444695,-1.0
96,37.405850,37.126381,36.688751,37.088064,36.876705,37.606694,90.650407,-11.428571,2.439024,-7128.045884,5.569457,27.232803,-1.0
97,37.283007,37.157092,36.763993,37.123508,36.915400,37.640482,88.725490,-22.857143,2.620456,5999.627181,-2.851546,30.779775,-1.0
98,37.160163,37.203158,36.817737,37.130173,36.938711,37.595142,87.027027,-6.060606,1.424979,-7828.987557,-2.025648,25.684081,-1.0
99,37.283007,37.221585,36.889907,37.157961,36.971501,37.606355,80.813953,-50.000000,2.274642,-17509.144689,1.815974,24.903105,-1.0

In [18]:
labels_features[labels_features.rsi_15<0]

Empty DataFrame
Columns: [Close, sma_10, sma_20, ema_10, ema_20, BB_15, rsi_15, williamsr_15, roc_15, adl_15, vpt_0, emv_0, label]
Index: []

In [19]:
labels_features[labels_features.williamsr_15<-100]

,Close,sma_10,sma_20,ema_10,ema_20,BB_15,rsi_15,williamsr_15,roc_15,adl_15,vpt_0,emv_0,label
834,36.730211,36.748637,36.676467,36.720475,36.582947,36.942533,61.240310,-100.0,0.419815,4.030423e+05,-0.080454,-11.750773,1.0
20547,99.318981,99.165427,98.737010,99.160609,98.761234,99.810025,70.529801,-100.0,0.653595,1.028423e+07,0.000000,15.129449,1.0
50523,43.503688,43.253417,43.022044,43.310087,43.178499,43.818757,69.667706,-100.0,1.845212,-9.828890e+04,0.000000,2847.990074,1.0
55217,53.811791,53.985643,53.860082,53.932348,53.876893,54.227205,67.884184,-100.0,0.021650,-1.956974e+05,-0.000017,7171.308173,1.0
55226,54.044742,53.839862,53.923346,53.905490,53.874331,54.215781,46.023468,-100.0,0.374240,-1.959412e+05,0.000312,6702.924341,1.0

In [34]:
import matplotlib.pyplot as plt
%matplotlib qt
from visualize.visualize import Visualizer
vl=Visualizer()

In [29]:
raw_data['High'].plot()
raw_data['Low'].plot()
plt.legend()

In [26]:
vl.share_plot(labels['close'],labels['return'],labels['volatility'])

In [35]:
vl.marker_plot(labels)

ValueError: not enough values to unpack (expected 4, got 2)

In [42]:
close=labels['close']
ret=labels['return']
vol=labels['volatility']
labs=labels['label']
up=close[labs==1.0]
down=close[labs==-1.0]

In [54]:
f, axarr = plt.subplots(2, 2,sharex='all')
axarr[0, 0].plot(close)
axarr[0, 0].set_title('Axis [0,0]')
axarr[0, 1].plot(ret)
axarr[0, 1].set_title('Axis [0,1]')
axarr[1, 0].plot(vol)
axarr[1, 0].set_title('Axis [1,0]')
axarr[1, 1].scatter(x, y ** 2)
axarr[1, 1].set_title('Axis [1,1]')

NameError: name 'x' is not defined

In [61]:
f, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, sharex='all')
f.suptitle('Sharing x per column, y per row')
ax1.plot(close)
ax2.plot(ret)
ax3.plot(vol)
close.plot(ax=ax4, alpha=.5)
up.plot(ax=ax4,ls='',marker='^', markersize=7,
     alpha=0.75, label='buy', color='g')
down.plot(ax=ax4,ls='',marker='v', markersize=7, 
       alpha=0.75, label='sell', color='r')
ax4.legend()

In [69]:
fig, axs = plt.subplots(ncols=3, nrows=3)
gs = axs[1, 2].get_gridspec()
# remove the underlying axes
for ax in axs[1:, -1]:
    ax.remove()
axbig = fig.add_subplot(gs[0:, -1])
axbig.annotate('Big Axes \nGridSpec[1:, -1]', (0.1, 0.5),
               xycoords='axes fraction', va='center')

fig.tight_layout()

In [ ]:
vl.compare_labels(labels,un_labels)

In [ ]:
df=labels_features

In [ ]:
def sharp_ratio(df,risk=0):
    close=df['Close']
    f_close=close.shift(-1)
    
    labs=df['label']
    ret_=((f_close/close)-1).dropna()
    
    ret_s=ret_.shift(-1)
    sharp_ratio=((ret_s*labs)-risk)/(ret_s*labs).std()
    
    df['return']=ret_
    df['sharp_ratio']=sharp_ratio
    
    return df

In [ ]:
labels_features.head()